#!/bin/bash
# Run Rubocop only for new, modified, or renamed files, and, in case of violations, it causes the commit to fail.
git status -s | sed -e ' s/.* \-\>/R /g' | grep -E 'A|M|R' | awk '{print $2}' | xargs rubocop --display-cop-names --extra-details --parallel --force-exclusion
